QTouchposeApplication: Fix keyWindow deprecated in iOS 13.0.
Lightricks/Touchpose pull request #8
Opened 2020-06-11 09:54 UTC by ShiraOzeri

2020-06-11 10:02 UTC, lior7 approved these changes
LGTM.

2020-06-11 10:10 UTC, lior7 requested changes
Fix and squash.

2020-06-11 10:10 UTC, lior7 commented on Touchpose/Touchpose/QTouchposeApplication.m
> +        for (UIWindow *window in [UIApplication sharedApplication].windows)
Can you use `self` instead of `[UIApplication sharedApplication]`? (is it the same object)

2020-06-11 10:17 UTC, ShiraOzeri commented
F&S

2020-06-11 10:43 UTC, lior7 approved these changes
LGTM.

2020-06-11 18:17 UTC, barakwei commented
It's a good question what the solution is, you can theoretically have multiple key windows if you have multiple scenes IIUC

2020-06-14 05:47 UTC, lior7 commented
@barakwei I think so too, but in Quickart we only have one, maybe we could continue looping and assert that there is one, or just leave it as the first one we got?

2020-06-14 09:48 UTC, barakwei commented
If it works for PF and QA feel free to merge. We'll find a proper solution later.

2020-06-14 10:25 UTC, lior7 commented
@barakwei great, I don't have permissions.

2020-06-14 10:28 UTC, merged